# This workflow runs the script at the lockdown dir
on:
  schedule:
  # Runs at 12:00 UTC every day (3PM Israel time)
  - cron: '0 12 * * *'
jobs:
  run_script:    
    # This section downloads the git and udpate it
    name: Download Products and Script From Git
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull master
      run: |
        git pull origin master
      shell: bash
#     This section runs the script from the lockdown dir
    - name: Run the script
      env:
        PYTHON_SCRIPT: "parse_denmark_files.py"
      run: |
        python $PYTHON_SCRIPT
      shell: bash
      working-directory: src/denmark_daily_update
    # This section updates the master to be with the new lockdown dir
    - name: Access User
      run: |
        git config --global user.email "ozvvizer@users.noreply.github.com"
        git config --global user.name "OzW1234"
      shell: bash
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Auto lockdown dir upload
        title: '[Denmark Workflow] Auto files upload'
        body: >
          This PR is auto-generated by denmark_files_script.yml
        labels: daily_update, automated pr
        branch: denmark_daily_autorun
