# This workflow runs a scraper of the israeli ministry of health website
on:
  schedule:
  # Runs at 7:00 and 19:00 UTC every day (10AM and 10PM Israel time)
  - cron: '23 9 * * *'
jobs:
  run_script:    
    # This section downloads the git and udpate it
    name: Download Products and Script From Git
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull master
      run: |
        git pull origin master
      shell: bash
#     This section runs the script
    - name: Run the script
      run: |
        python imh_website_scraper.py
      shell: bash
      working-directory: ./src/israeli_health_ministry_telegram
    # This section updates the master to be with the new lockdown dir
    - name: Access User
      run: |
        git config --global user.email "ozvvizer@users.noreply.github.com"
        git config --global user.name "OzW1234"
      shell: bash
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Auto israeli website scraper dir upload
        title: '[IMH Website Scraper] Auto files upload'
        body: >
          This PR is auto-generated by imh_website_scraper.yml
        labels: daily_update, automated pr
        branch: israeli_website_scraper_daily_autorun
