on:
  schedule:
  - cron: 52 15 * * *

jobs: 
  download_updates:
    name: Downloads the daily new updates of the israeli health ministry 
    runs-on: windows-latest
    steps:
    - name: Clone git
      uses: actions/checkout@master
      with:
        ref: develop
        token: ${{ secrets.PAT }}
        submodules: true
