# This workflow runs the script at the lockdown dir
on:
  schedule:
  # Runs at 00:00 UTC every day
  - cron: '30 14 * * *'
jobs:
  clone_git:
    # This job downloads the git and udpate it
    name: Download Products and Script From Git
    runs-on: windows-latest
    steps:
    - name: Clone git
      env:
        GIT_URL: "https://github.com/COVID-19-Israel/Covid-19-data.git"
      run: |
        git clone $GIT_URL
      shell: bash
    - name: test
      env: 
        GIT_DIR: Covid-19-data
      run: |
        ls
        cd $GIT_DIR
        pwd
        ls
      shell: bash
    - name: Pull master
      run: |
        git pull origin master
      shell: bash
  run_script:
    # This job runs the script from the lockdown dir
    name: Run The Script From The Lockdown Dir
    needs: clone_git 
    runs-on: windows-latest
    steps:
    - name: Get into the lockdown dir
      env:
        LOCKDOWN_DIR: Lockdown
      run: |
        cd $LOCKDOWN_DIR
      shell: bash
    - name: Run the script
      env:
        PYTHON_SCRIPT: diffs_to_states 1.5.2.py
        OUTPUT_DIR: output
        BACKUP_DIR: backup
        OUTPUT_FILE: all_states.csv
        PROVINCES_FILE: explored_areas.csv
      run: |
        mkdir -p $OUTPUT_DIR
        mkdir -p $BACKUP_DIR
        cp $OUTPUT_FILE $BACKUP_DIR
        python $PYTHON_SCRIPT -i . -c $PROVINCES_FILE -o $OUTPUT_DIR/$OUTPUT_FILE
      shell: bash
  update_changes:
    # This job updates the master to be with the new lockdown dir
    name: Updates The Changes That The script Made
    needs: [clone_git, run_script]
    runs-on: windows-latest
    steps:
      - name: Add the lockdown dir with the changes
        env:
          LOCKDOWN_DIR: Lockdown
        run: |
          cd ..
          git init
          git add $LOCKDOWN_DIR
          git commit -m "Auto upload new lockdown dir"
        shell: bash
      - name: Push the changes to git
        run: |
          git push origin master
        shell: bash
