# This workflow runs the script at the lockdown dir
on:
  schedule:
  # Runs at 22:00 UTC every day (1AM Israel time)
  - cron: '0 22 * * *'
jobs:
  run_script:    
    # This section downloads the git and udpate it
    name: Download Products and Script From Git
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull master
      run: |
        git pull origin master
      shell: bash
#     This section runs the script from the lockdown dir
    - name: Add Dirs For Script
      env:
        OUTPUT_DIR: "output"
        BACKUP_DIR: "backup"
      run: |
        mkdir -p $OUTPUT_DIR
        mkdir -p $BACKUP_DIR
      shell: bash
      working-directory: data/lockdown
    - name: Run the script
      env:
        SCRIPT_DIR: "src/lockdownStatesParser"
        PYTHON_SCRIPT: "diffs_to_states.py"
        OUTPUT_DIR: "data/lockdown/output"
        BACKUP_DIR: "data/lockdown/backup"
        OUTPUT_FILE: "all_states.csv"
        INPUT_DIR: "data/lockdown"
        PROVINCES_FILE: "utils/explored_areas.csv"
      run: |
        cp $OUTPUT_DIR/$OUTPUT_FILE $BACKUP_DIR
        python $SCRIPT_DIR/$PYTHON_SCRIPT -i $INPUT_DIR -c $INPUT_DIR/$PROVINCES_FILE -o $OUTPUT_DIR/$OUTPUT_FILE
      shell: bash
    # This section updates the master to be with the new lockdown dir
    - name: Add the lockdown dir with the changes
      env:
        LOCKDOWN_DIR: ./data/lockdown
      run: |
        git config --global user.email "ozvvizer@users.noreply.github.com"
        git config --global user.name "OzW1234"
      shell: bash
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Auto lockdown dir upload
        title: '[Lockdown Workflow] Auto files upload'
        body: >
          This PR is auto-generated by lockdown_script_autorun.yml
        labels: daily_update, automated pr
        branch: lockdown_daily_autorun
