# This workflow runs the script at the lockdown dir
on:
  schedule:
  # Runs at 00:00 UTC every day
  - cron: '30 14 * * *'
jobs:
  run_script:
    # This section downloads the git and udpate it
    name: Download Products and Script From Git
    runs-on: windows-latest
    steps:
    - name: Clone git
      env:
        GIT_URL: "https://github.com/COVID-19-Israel/Covid-19-data.git"
      run: |
        git clone $GIT_URL
      shell: bash
    - name: Pull master
      run: |
        git pull origin master
      shell: bash
      working-directory: ./Covid-19-data
#     This section runs the script from the lockdown dir
    - name: Add Dirs For Script
      env:
        OUTPUT_DIR: "output"
        BACKUP_DIR: "backup"
      run: |
        mkdir -p $OUTPUT_DIR
        mkdir -p $BACKUP_DIR
      shell: bash
      working-directory: ./Covid-19-data/Lockdown
    - name: Run the script
      env:
        PYTHON_SCRIPT: "diffs_to_states.py"
        OUTPUT_DIR: "output"
        BACKUP_DIR: "backup"
        OUTPUT_FILE: "all_states.csv"
        PROVINCES_FILE: "utils/explored_areas.csv"
      run: |
        cp $OUTPUT_DIR/$OUTPUT_FILE $BACKUP_DIR
        python $PYTHON_SCRIPT -i . -c $PROVINCES_FILE -o $OUTPUT_DIR/$OUTPUT_FILE
      shell: bash
      working-directory: ./Covid-19-data/Lockdown
    # This section updates the master to be with the new lockdown dir
    - name: Add the lockdown dir with the changes
      env:
        LOCKDOWN_DIR: Lockdown
      run: |
        git config --global user.email "ozvvizer@gmail.com"
        git config --global user.name "OzW1234"
        git init
        git add $LOCKDOWN_DIR
        git commit -m "Auto upload new lockdown dir"
      shell: bash
      working-directory: ./Covid-19-data
    - name: Push the changes to git
      run: |
        git push origin master
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
