# This is a basic workflow to help you get started with Actions

name: scrapeRunner 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "20 21 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Clone git
      env:
        GIT_URL: "https://github.com/COVID-19-Israel/Covid-19-data.git"
      run: |
        git clone $GIT_URL
      shell: bash
    - name: Pull master
      run: |
        git pull origin master
      shell: bash
      working-directory: ./Covid-19-data
    # Runs a single command using the runners shell
    - name: install dependencies
      run: |
        pip install requests
        pip install bs4
    # Runs a set of commands using the runners shell
    - name: Run scraper
      run: python worldmeterScraper.py
      working-directory: ./Covid-19-data/worldmeterScraper
      # This section updates the master to be with the new lockdown dir
    - name: Add the scraper dir with the changes
      env:
        DIR_TO_ADD: worldmeterScraper/
      run: |
        git config --global user.email "eyaldvir@users.noreply.github.com"
        git config --global user.name "Pass7632"
        git init
        git add $DIR_TO_ADD
        git commit -m "Auto daily run of worldmeterScraper"
      shell: bash
      working-directory: ./Covid-19-data
    - name: Push the changes to git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git push github HEAD:${GITHUB_REF}
      working-directory: ./Covid-19-data
      shell: bash
